properties([
  buildDiscarder(logRotator(numToKeepStr: '50')),
  disableConcurrentBuilds()
])

node {
  checkout scm

  stage('Docker system prune') {
    dir ('ENISA-UI') {
      sh """docker system prune -f"""
    }
  }
  stage('Build docker image') {
    dir ('ENISA-UI') {
      sh """docker build -t webapp ."""
    }
  }

  stage("Stop docker container") {
    dir ('ENISA-UI') {
        sh """docker kill webapp || true"""
    }
  }

  stage("Run docker container") {
    dir ('ENISA-UI') {
        sh """docker run -d --rm --name webapp -p 4200:4200 webapp"""
    }
  }

  stage("Verify docker container") {
    dir ('ENISA-UI') {
        sh """docker ps | grep webapp"""
    }
  }
}
